In [2]:
import numpy as np

In [3]:
type([1,2,3])

list

In [4]:
arr=np.array([1,2,3])

In [5]:
arr

array([1, 2, 3])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(3,)

In [11]:
arr.ndim

1

In [8]:
arr.size

3

In [10]:
arr.dtype

dtype('int32')

In [40]:
arr1=np.array([[1,2],[3,4]])

In [41]:
arr1

array([[1, 2],
       [3, 4]])

In [14]:
arr1.shape

(2, 2)

In [15]:
arr1.size

4

In [17]:
arr1.ndim

2

In [18]:
type(arr1)

numpy.ndarray

In [36]:
arr2=np.array([[1,2],[3,4,5]])

C:\Users\manis\AppData\Local\Temp\ipykernel_1604\2246275856.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2=np.array([[1,2],[3,4,5]])


In [37]:
arr2

array([list([1, 2]), list([3, 4, 5])], dtype=object)

In [23]:
dict1={
'first_name':'manish',
'last_name':'kharbuja'
}

In [24]:
type(dict1)

dict

In [33]:
dict1.items()

dict_items([('first_name', 'manish'), ('last_name', 'kharbuja')])

In [28]:
result=dict1.items()

In [29]:
data=list(result)

In [30]:
arr3=np.array(data)

In [32]:
arr3

array([['first_name', 'manish'],
       ['last_name', 'kharbuja']], dtype='<U10')

In [34]:
arr3.shape

(2, 2)

In [42]:
arr1

array([[1, 2],
       [3, 4]])

In [45]:
arr1[:,1]

array([2, 4])

In [46]:
arr

array([1, 2, 3])

In [47]:
arr[1]

2

In [48]:
arr[-2]

2

In [49]:
arr[-4]

IndexError: index -4 is out of bounds for axis 0 with size 3

In [50]:
arr1[0,0]

1

In [52]:
arr1[0][0]

1